
services:
  neo4j:
    image: neo4j:5.26.1
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # graphical interface port
      - "7687:7687"  # backend apps port
    environment:
      NEO4J_AUTH: neo4j/CharlotteQa$
      NEO4J_dbms_memory_pagecache_size: 512M
      NEO4J_dbms_memory_heap_initial__size: 512M
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4JLABS_PLUGINS: '["apoc", "graph-data-science"]'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/conf
    networks:
      - neo4j_network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:

networks:
  neo4j_network:
    driver: bridge 